AWSTemplateFormatVersion: "2010-09-09"
Description: YouTube Live Metadata Notification - CI/CD Pipeline AWS Resources

Parameters:
  ArtifactS3BucketName:
    Type: String
    Description: S3 Bucket Name for CodeBuild Artifact

  GitHubOwnerName:
    Type: String
    Description: GitHub Repository Owner Name

  GitHubPAT:
    Type: String
    Description: GitHub Personal Access Token
    NoEcho: true

  GitHubRepositoryName:
    Type: String
    Description: GitHub Repository Name

  YouTubeChannelId:
    Type: String
    Description: YouTube Channel ID to Monitor for Live Streams

Resources:
  # Systems Manager Parameter for YouTube Channel ID
  YouTubeChannelIdSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /ytlivemetadata/youtube_channel_id
      Type: String
      Value: !Ref YouTubeChannelId
      Description: YouTube Channel ID to Monitor for Live Streams

  # S3 Bucket for CodeBuild Artifact
  ArtifactS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ArtifactS3BucketName
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: ExpireArtifactsFast
            Status: Enabled
            ExpirationInDays: 1
            NoncurrentVersionExpiration:
              NoncurrentDays: 1
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
    DeletionPolicy: Retain

  # S3 Bucket Policy for CodeBuild Artifact
  ArtifactS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ArtifactS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCodePipelineCodeBuildAndCloudFormationAccess
            Effect: Allow
            Principal:
              AWS:
                - !GetAtt CodePipelineServiceRole.Arn
                - !GetAtt CodeBuildServiceRole.Arn
                - !GetAtt CloudFormationExecutionRole.Arn
            Action:
              - "s3:GetObject"
              - "s3:PutObject"
              - "s3:GetObjectVersion"
              - "s3:ListBucket"
              - "s3:GetBucketLocation"
              - "s3:GetBucketVersioning"
            Resource:
              - !GetAtt ArtifactS3Bucket.Arn
              - !Sub "${ArtifactS3Bucket.Arn}/*"
          - Sid: DenyUnEncryptedObjectUploads
            Effect: Deny
            Principal: "*"
            Action: "s3:PutObject"
            Resource: !Sub "${ArtifactS3Bucket.Arn}/*"
            Condition:
              StringNotEquals:
                "aws:PrincipalArn":
                  - !GetAtt CodePipelineServiceRole.Arn
                  - !GetAtt CodeBuildServiceRole.Arn
                  - !GetAtt CloudFormationExecutionRole.Arn
                "s3:x-amz-server-side-encryption": "AES256"

  # CloudWatch Logs for CodeBuild
  CodeBuildLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/codebuild/ytlivemetadata-build
      RetentionInDays: 90

  # IAM Role for AWS CodeBuild
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ytlivemetadata-role-codebuild
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: CodeBuildCloudWatchLogsPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*"
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*:*"

  # AWS CodeBuild
  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: "ytlivemetadata-build"
      Description: Build Project for YouTube Live Metadata Notification
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux-x86_64-standard:5.0
        PrivilegedMode: false
        EnvironmentVariables:
          - Name: ARTIFACT_BUCKET
            Value: !Ref ArtifactS3Bucket
      Source:
        Type: CODEPIPELINE
        BuildSpec: templates/buildspec.yml
      TimeoutInMinutes: 10

  # IAM Role for AWS CodePipeline
  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ytlivemetadata-role-codepipeline
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: CodePipelineCodeBuildExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "codebuild:BatchGetBuilds"
                  - "codebuild:StartBuild"
                Resource: !GetAtt BuildProject.Arn
        - PolicyName: CodePipelineCloudFormationExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "cloudformation:CreateStack"
                  - "cloudformation:DeleteStack"
                  - "cloudformation:DescribeStacks"
                  - "cloudformation:UpdateStack"
                  - "cloudformation:CreateChangeSet"
                  - "cloudformation:DeleteChangeSet"
                  - "cloudformation:DescribeChangeSet"
                  - "cloudformation:ExecuteChangeSet"
                  - "cloudformation:SetStackPolicy"
                  - "cloudformation:ValidateTemplate"
                  - "cloudformation:GetTemplate"
                Resource: !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/ytlivemetadata-stack-sam/*"
        - PolicyName: CodePipelineGitHubConnectionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "codestar-connections:UseConnection"
                Resource: "*"
        - PolicyName: CodePipelineIAMPassRolePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "iam:PassRole"
                Resource: !GetAtt CloudFormationExecutionRole.Arn

  # AWS CloudFormation Execution Role
  CloudFormationExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ytlivemetadata-role-cloudformation-execution
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: CloudFormationResourceAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "apigateway:*"
                Resource:
                  - !Sub "arn:aws:apigateway:${AWS::Region}::/account"
                  - !Sub "arn:aws:apigateway:${AWS::Region}::/restapis"
                  - !Sub "arn:aws:apigateway:${AWS::Region}::/restapis/*"
              - Effect: Allow
                Action: "cloudformation:*"
                Resource: !Sub "arn:aws:cloudformation:${AWS::Region}:aws:transform/Serverless-2016-10-31"
              - Effect: Allow
                Action: "dynamodb:*"
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/ytlivemetadata-dynamodb"
              - Effect: Allow
                Action: "events:*"
                Resource: !Sub "arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/ytlivemetadata-ebrule-websub"
              - Effect: Allow
                Action: "iam:*"
                Resource:
                  - !Sub "arn:aws:iam::${AWS::AccountId}:role/ytlivemetadata-lambda-get-notify-*"
                  - !Sub "arn:aws:iam::${AWS::AccountId}:role/ytlivemetadata-lambda-post-notify-*"
                  - !Sub "arn:aws:iam::${AWS::AccountId}:role/ytlivemetadata-lambda-websub-*"
                  - !Sub "arn:aws:iam::${AWS::AccountId}:role/ytlivemetadata-stack-sam-*"
                  - !Sub "arn:aws:iam::${AWS::AccountId}:role/ytlivemetadata-role-apigateway-cloudwatch-logs"
                  - !Sub "arn:aws:iam::${AWS::AccountId}:role/ytlivemetadata-role-sns-cloudwatch-logs"
              - Effect: Allow
                Action: "lambda:*"
                Resource:
                  - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:ytlivemetadata-lambda-get-notify"
                  - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:ytlivemetadata-lambda-post-notify"
                  - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:ytlivemetadata-lambda-websub"
                  - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:ytlivemetadata-lambda-layer"
                  - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:ytlivemetadata-lambda-layer:*"
              - Effect: Allow
                Action: "logs:*"
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*"
              - Effect: Allow
                Action: "ssm:*"
                Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ytlivemetadata/*"
        - PolicyName: CloudFormationIAMPassRolePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "iam:PassRole"
                Resource: "*"
                Condition:
                  StringEquals:
                    "iam:PassedToService":
                      - "lambda.amazonaws.com"
                      - "apigateway.amazonaws.com"

  # AWS CodePipeline
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: "ytlivemetadata-pipeline"
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactS3Bucket
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: "1"
              Configuration:
                Owner: !Ref GitHubOwnerName
                Repo: !Ref GitHubRepositoryName
                Branch: main
                OAuthToken: !Ref GitHubPAT
              OutputArtifacts:
                - Name: SourceCode
        - Name: Build
          Actions:
            - Name: TestAndBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: !Ref BuildProject
              InputArtifacts:
                - Name: SourceCode
              OutputArtifacts:
                - Name: BuildOutput
        - Name: Deploy
          Actions:
            - Name: DeployToCloudFormation
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: ytlivemetadata-stack-sam
                TemplatePath: BuildOutput::packaged.yaml
                Capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                RoleArn: !GetAtt CloudFormationExecutionRole.Arn
              InputArtifacts:
                - Name: BuildOutput
