AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: YouTube Live Metadata Notification - Serverless Application AWS Resources

Globals:
  Function:
    Runtime: python3.12
    Timeout: 120
    MemorySize: 256
    Tracing: Active
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: ytlivemetadata
        LOG_LEVEL: INFO

Resources:
  # CloudWatch Logs for API Gateway Access Logs
  ApiGatewayAccessLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/apigateway/ytlivemetadata-apig
      RetentionInDays: 90

  # CloudWatch Logs for Lambda Function to Handle WebSub Subscription Verification
  GetNotifyLambdaFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/ytlivemetadata-lambda-get-notify
      RetentionInDays: 90

  # CloudWatch Logs for Lambda Function to Process WebSub Notifications and Send SMS
  PostNotifyLambdaFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/ytlivemetadata-lambda-post-notify
      RetentionInDays: 90

  # CloudWatch Logs for Lambda Function to Renew Google PubSubHubbub Subscription
  WebSubLambdaFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/ytlivemetadata-lambda-websub
      RetentionInDays: 90

  # DynamoDB Table
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ytlivemetadata-dynamodb
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: video_id
          AttributeType: S
      KeySchema:
        - AttributeName: video_id
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # SNS Topic for SMS Notifications
  SnsTopicForSms:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ytlivemetadata-sns
      DisplayName: YouTube Live Metadata Notifications

  # Lambda Function for WebSub Subscription Verification
  GetNotifyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ytlivemetadata-lambda-get-notify
      CodeUri: ../lambdas/get_notify/
      Handler: app.lambda_handler
      Description: Handle WebSub Subscription Verification for YouTube Live Stream Notifications
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - ssm:DescribeParameters
                - ssm:GetParameter
                - ssm:GetParameters
              Resource:
                - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ytlivemetadata/websub_hmac_secret"
                - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ytlivemetadata/youtube_channel_id"
      Environment:
        Variables:
          WEBSUB_HMAC_SECRET_PARAMETER_NAME: "/ytlivemetadata/websub_hmac_secret"
          YOUTUBE_CHANNEL_ID_PARAMETER_NAME: "/ytlivemetadata/youtube_channel_id"
      Events:
        ApiEventGet:
          Type: Api
          Properties:
            Path: /notify
            Method: get
            RestApiId: !Ref ApiGateway
      LoggingConfig:
        LogGroup: !Ref GetNotifyLambdaFunctionLogs

  # Lambda Function to Process WebSub Notifications and Send SMS
  PostNotifyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ytlivemetadata-lambda-post-notify
      CodeUri: ../lambdas/post_notify/
      Handler: app.lambda_handler
      Description: Process YouTube Live Stream Notifications and Send SMS
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
              Resource: !GetAtt DynamoDBTable.Arn
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: "*"
            - Effect: Allow
              Action:
                - ssm:DescribeParameters
                - ssm:GetParameter
                - ssm:GetParameters
              Resource:
                - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ytlivemetadata/phone_number"
                - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ytlivemetadata/websub_hmac_secret"
                - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ytlivemetadata/youtube_api_key"
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DynamoDBTable
          SMS_PHONE_NUMBER_PARAMETER_NAME: "/ytlivemetadata/phone_number"
          SNS_TOPIC_ARN: !Ref SnsTopicForSms
          WEBSUB_HMAC_SECRET_PARAMETER_NAME: "/ytlivemetadata/websub_hmac_secret"
          YOUTUBE_API_KEY_PARAMETER_NAME: "/ytlivemetadata/youtube_api_key"
      Events:
        ApiEventPost:
          Type: Api
          Properties:
            Path: /notify
            Method: post
            RestApiId: !Ref ApiGateway
      LoggingConfig:
        LogGroup: !Ref PostNotifyLambdaFunctionLogs

  # Lambda Function to Renew Google PubSubHubbub Subscription
  WebSubLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ytlivemetadata-lambda-websub
      CodeUri: ../lambdas/websub/
      Handler: app.lambda_handler
      Description: Renew Google PubSubHubbub Subscription
      Environment:
        Variables:
          PUBSUBHUBBUB_HUB_URL: "https://pubsubhubbub.appspot.com/"
          LEASE_SECONDS: "828000"
          HMAC_SECRET_LENGTH: "32"
          WEBSUB_CALLBACK_URL_PARAMETER_NAME: "/ytlivemetadata/websub_callback_url"
          WEBSUB_HMAC_SECRET_PARAMETER_NAME: "/ytlivemetadata/websub_hmac_secret"
          YOUTUBE_CHANNEL_ID_PARAMETER_NAME: "/ytlivemetadata/youtube_channel_id"
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - ssm:DescribeParameters
                - ssm:GetParameter
                - ssm:GetParameters
              Resource:
                - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ytlivemetadata/websub_callback_url"
                - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ytlivemetadata/youtube_channel_id"
            - Effect: Allow
              Action:
                - ssm:PutParameter
              Resource:
                - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ytlivemetadata/websub_hmac_secret"
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: rate(7 days)
            Name: ytlivemetadata-ebrule-websub
            Description: Schedule to Refresh Google PubSubHubbub Subscription Before It Expires
      LoggingConfig:
        LogGroup: !Ref WebSubLambdaFunctionLogs

  # IAM Role for API Gateway CloudWatch Logs
  ApiGatewayCloudWatchLogsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs"

  # API Gateway Account Configuration
  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt ApiGatewayCloudWatchLogsRole.Arn

  # API Gateway
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: ytlivemetadata-apig
      StageName: prod
      EndpointConfiguration:
        Type: REGIONAL
      Auth:
        DefaultAuthorizer: NONE
      AccessLogSetting:
        DestinationArn: !GetAtt ApiGatewayAccessLogs.Arn
        Format: '{ "requestId":"$context.requestId", "ip": "$context.identity.sourceIp", "requestTime":"$context.requestTime", "httpMethod":"$context.httpMethod", "routeKey":"$context.routeKey", "status":"$context.status", "protocol":"$context.protocol", "responseLength":"$context.responseLength" }'
      MethodSettings:
        - LoggingLevel: "OFF"
          ResourcePath: "/*"
          HttpMethod: "*"
          DataTraceEnabled: false
          MetricsEnabled: true

  # Systems Manager Parameter for Google PubSubHubbub Callback URL
  WebSubCallbackUrlSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /ytlivemetadata/websub_callback_url
      Type: String
      Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/notify
      Description: Google PubSubHubbub Callback URL
