name: Run Tests and Lint in Lambda Functions before Merging Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/test-lint-lambdas.yaml
      - lambdas/**
      - pyproject.toml
      - uv.lock
      - pytest.ini

env:
  PYTHON_VERSION: "3.12"
  AWS_DEFAULT_REGION: ap-northeast-1
  PYTHONPATH: lambdas/layer/python

permissions:
  checks: write
  pull-requests: write
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          enable-cache: true
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: uv sync --locked --all-groups

      - name: Run unittests with coverage
        run: |
          uv run pytest --cov=lambdas --cov-report=term-missing --cov-fail-under=80 lambdas/tests

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          enable-cache: true
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: uv sync --locked --all-groups

      - name: Run lint
        run: uv run pylint lambdas/**/*.py
